name: mindrev
description: A study app
repository: https://github.com/ScratchX98/Mindrev

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.0
  responsive_framework: ^0.1.4
  selectable: ^0.1.2
  hexcolor: ^2.0.5
  toml: ^0.12.0
  flutter_spinkit: ^5.1.0
  path: ^1.8.0
  flutter_material_color_picker: ^1.1.0+2
  path_provider: ^2.0.9
  flutter_svg: ^1.0.0
  rflutter_alert: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_linkify: ^5.0.2
  flash_card: ^0.0.7
  scroll_snap_list: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - text/
    - assets/study_material_icons/

  fonts:
    - family: SourceSansPro
      fonts:
       - asset: assets/fonts/SourceSansPro-Bold.ttf
       - asset: assets/fonts/SourceSansPro-Italic.ttf
       - asset: assets/fonts/SourceSansPro-Regular.ttf
