name: mindrev
description: A study software

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  responsive_framework: ^0.1.4
  selectable: ^0.1.2
  easy_sidemenu: ^0.1.1+1
  hexcolor: ^2.0.5
  toml: ^0.12.0
  flutter_spinkit: ^5.1.0
  path: ^1.8.0
  flutter_material_color_picker: ^1.1.0+2
  objectdb: ^1.2.1+1
  path_provider: ^2.0.8
  sembast: ^3.1.1+1
  sembast_web: ^2.0.1+1
  flutter_svg: ^1.0.0
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - text/
    - assets/study_material_icons/

  fonts:
    - family: Montserrat
      fonts:
       - asset: assets/fonts/Montserrat-Medium.ttf

    - family: Comfortaa-Bold
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
