materials = [
	{name = "Notes", icon = "notes"},
	{name = "Ordered notes", icon = "ordered_notes"},
	{name = "Flashcards", icon = "flashcards"},
	{name = "Graphs", icon = "graphs"},
	{name = "Mind-map", icon = "mind_map"},
]
