materials = [
	{name = "Notes", icon = "notes"},
	{name = "Ordered notes", icon = "orderedNotes"},
	{name = "Flashcards", icon = "flashcards"},
	{name = "Graphs", icon = "graphs"},
	{name = "Mind-map", icon = "mindMap"},
]
