[themes.mindrev]
name = "Default"
primary = "#FAFAFA"
primaryText = "#0B0B0B"
secondary = "#212121"
secondaryText = "#FAFAFA"
accent = "#03A9F4"
accentText = "#FAFAFA"

[themes.dark]
name = "Dark"
primary = "#242323"
primaryText = "#FAFAFA"
secondary = "#171717"
secondaryText = "#FAFAFA"
accent = "#03A9F4"
accentText = "#FAFAFA"

[themes.light]
name = "Light"
primary = "#FAFAFA"
primaryText = "#0B0B0B"
secondary = "#F5F5F5"
secondaryText = "#0B0B0B"
accent = "#4FC7FD"
accentText = "#0B0B0B"

[themes.spacegray]
name = "SpaceGray"
primary = "#2B303B"
primaryText = "#C0C5CE"
secondary = "#232830"
secondaryText = "#C0C5CE"
accent = "#8FA1B3"
accentText = "#232830"

[themes.solarized]
name = "Solarized Dark"
primary = "#073642"
primaryText = "#FDF6E3"
secondary = "#002B36"
secondaryText = "#EEE8D5"
accent = "#B58900"
accentText = "#002B36"

[themes.solarizedLight]
name = "Solarized Light"
primary = "#fdf6e3"
primaryText = "#657b83"
secondary = "#eee8d5"
secondaryText = "#657b83"
accent = "#073642"
accentText = "#93a1a1"

[themes.andromeda]
name = "Andromeda"
primary = "#D5CED9"
primaryText = "#23262e"
secondary = "#23262e"
secondaryText = "#D5CED9"
accent = "#07c1a6"
accentText = "#23262e"

[themes.darcula]
name = "Darcula"
primary = "#313335"
primaryText = "#AFB1B3"
secondary = "#2B2B2B"
secondaryText = "#AFB1B3"
accent = "#C96A2E"
accentText = "#2B2B2B"

[themes.monokai]
name = "Monokai"
primary = "#3B3539"
primaryText = "#FCFCFA"
secondary = "#2D2A2E"
secondaryText = "#FCFCFA"
accent = "#F4CE63"
accentText = "#2D2A2E"

[themes.tokyonight]
name = "Tokyonight"
primary = "#24283b"
primaryText = "#cfc9c2"
secondary = "#1a1b26"
secondaryText = "#cfc9c2"
accent = "#bb9af7"
accentText = "#cfc9c2"

[themes.nord]
name = "Nord"
primary = "#3b4252"
primaryText = "#eceff4"
secondary = "#2e3440"
secondaryText = "#eceff4"
accent = "#88c0d0"
accentText = "#4c566a"

[themes.polar]
name = "Polar"
primary = "#e5e9f0"
primaryText = "#434c5e"
secondary = "#d8dee9"
secondaryText = "#434c5e"
accent = "#88c0d0"
accentText = "#4c566a"

[themes.reeder]
name = "Reeder"
primary = "#F9F8F6"
primaryText = "#635240"
secondary = "#E8E8E8"
secondaryText = "#635240"
accent = "#FC7302"
accentText = "#F9F8F6"

