[themes]
mindrev.name = "Default"
mindrev.primary = "#FAFAFA"
mindrev.primaryText = "#0B0B0B"
mindrev.secondary = "#212121"
mindrev.secondaryText = "#FAFAFA"
mindrev.accent = "#03A9F4"
mindrev.accentText = "#FAFAFA"

dark.name = "Dark"
dark.primary = "#242323"
dark.primaryText = "#FAFAFA"
dark.secondary = "#171717"
dark.secondaryText = "#FAFAFA"
dark.accent = "#03A9F4"
dark.accentText = "#FAFAFA"

light.name = "Light"
light.primary = "#FAFAFA"
light.primaryText = "#0B0B0B"
light.secondary = "#F5F5F5"
light.secondaryText = "#0B0B0B"
light.accent = "#4FC7FD"
light.accentText = "#0B0B0B"

spacegray.name = "SpaceGray"
spacegray.primary = "#2B303B"
spacegray.primaryText = "#C0C5CE"
spacegray.secondary = "#232830"
spacegray.secondaryText = "#C0C5CE"
spacegray.accent = "#8FA1B3"
spacegray.accentText = "#232830"

solarized.name = "Solarized Dark"
solarized.primary = "#073642"
solarized.primaryText = "#FDF6E3"
solarized.secondary = "#002B36"
solarized.secondaryText = "#EEE8D5"
solarized.accent = "#B58900"
solarized.accentText = "#002B36"

solarizedLight.name = "Solarized Light"
solarizedLight.primary = "#fdf6e3"
solarizedLight.primaryText = "#657b83"
solarizedLight.secondary = "#eee8d5"
solarizedLight.secondaryText = "#657b83"
solarizedLight.accent = "#073642"
solarizedLight.accentText = "#93a1a1"

andromeda.name = "Andromeda"
andromeda.primary = "#D5CED9"
andromeda.primaryText = "#23262e"
andromeda.secondary = "#23262e"
andromeda.secondaryText = "#D5CED9"
andromeda.accent = "#07c1a6"
andromeda.accentText = "#23262e"

darcula.name = "Darcula"
darcula.primary = "#313335"
darcula.primaryText = "#AFB1B3"
darcula.secondary = "#2B2B2B"
darcula.secondaryText = "#AFB1B3"
darcula.accent = "#C96A2E"
darcula.accentText = "#2B2B2B"

monokai.name = "Monokai"
monokai.primary = "#3B3539"
monokai.primaryText = "#FCFCFA"
monokai.secondary = "#2D2A2E"
monokai.secondaryText = "#FCFCFA"
monokai.accent = "#F4CE63"
monokai.accentText = "#2D2A2E"

tokyonight.name = "Tokyonight"
tokyonight.primary = "#24283b"
tokyonight.primaryText = "#cfc9c2"
tokyonight.secondary = "#1a1b26"
tokyonight.secondaryText = "#cfc9c2"
tokyonight.accent = "#bb9af7"
tokyonight.accentText = "#cfc9c2"

nord.name = "Nord"
nord.primary = "#3b4252"
nord.primaryText = "#eceff4"
nord.secondary = "#2e3440"
nord.secondaryText = "#eceff4"
nord.accent = "#88c0d0"
nord.accentText = "#4c566a"

polar.name = "Polar"
polar.primary = "#e5e9f0"
polar.primaryText = "#434c5e"
polar.secondary = "#d8dee9"
polar.secondaryText = "#434c5e"
polar.accent = "#88c0d0"
polar.accentText = "#4c566a"


