[sidebar]
home = "Home"
settings = "Settings"
help = "Help"
about = "About"
header = "Hello!"

[home]
create = "It seems like you haven't created any classes yet, click the button below to get started"
new = "Class"

[about]
title = "About"
close = "Close"
version = "Version"
versionNumber = "Alpha 0.1"
author = "Author"
source = "Source Code"
license = "License"

[newClass]
title = "Create a new class"
label = "Class name"
submit = "Submit"
cancel = "Cancel"
errorNoText = "Please enter some text"
chooseColor = "Choose a color"
chooseColorDetails = "Choose a color for your new class"

[settings]
title = "Settings"
apply = "Apply"
ui = "User interface"
uiColors = "Would you like the accent color of the application to change with the selected class?"
confetti = "Would you like confetti effects to be displayed?"
theme = "Theme"
language = "Language"

[topics]
create = "It seems like you haven't created any topics yet, click the button below to get started"
new = "Topic"

[newTopic]
title = "Create a new topic"
label = "Topic name"
submit = "Submit"
errorNoText = "Please enter some text"

[classExtra]
creationDate = "Creation date"
delete = "Delete class"
rename = "Rename class"
newName = "New name"
errorNoText = "Please enter some text"
sure = "Are you sure you want to delete"
confirm = "Delete"
cancel = "Cancel"

[materials]
create = "It seems like you don't have any material to study yet, click the button below to get started"
new = "Material"

[newMaterial]
title = "Create some new study material"
label = "Material name"
submit = "Submit"
errorNoText = "Please enter some text"
type = "Choose a material type"
duplicate = "Looks like a material with that name already exists"
close = "Close"

[topicExtra]
creationDate = "Creation date"
delete = "Delete topic"
rename = "Rename topic"
newName = "New name"
errorNoText = "Please enter some text"
sure = "Are you sure you want to delete"
confirm = "Delete"
cancel = "Cancel"

[materialExtra]
creationDate = "Creation date"
delete = "Delete material"
rename = "Rename material"
newName = "New name"
errorNoText = "Please enter some text"
sure = "Are you sure you want to delete"
confirm = "Delete"
cancel = "Cancel"

[flashcards]
learn = "Learn"
practice = "Practice"
quiz = "Quiz"
new = "Flashcards"
create = "It seems like you haven't created any flashcards yet, click the button below to get started"
termOrDef = "Term or definition"
termOrDefDesc = "What would you like to see first?"
term = "Term"
def = "Definition"

[newFlashcards]
title = "New Flashcards"
new = "Flashcard"
front = "Front"
back = "Back"

[learnFlashcards]
title = "Learn"

[practiceFlashcards]
title = "Practice"
term = "Term"
def = "Definition"
perfect = "Correct!"
right = "Typo, precise answer"
wrong = "Not quite"
correctAnswer = "Correct answer"
next = "Next"

[quizFlashcards]
title = "Quiz"
term = "Term"
def = "Definition"
perfect = "Correct!"
right = "Typo"
wrong = "Not quite"
close = "Close"
results = "Quiz results"
question = "Question"
correctAnswer = "Correct answer"
responded = "Your answer"